import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import style from "./style/responsive.css"
import { Footer } from "./Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
            <Script
        src="https://www.googletagmanager.com/gtag/js?id=G-9753K5TW0E"
        strategy="afterInteractive"
      />
      <Script id="google-analytics" strategy="afterInteractive">
        {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
          gtag('config', 'G-9753K5TW0E', {
            page_path: window.location.pathname,
          });
        `}
      </Script>
      <body className={inter.className}>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
